name: Build With CMake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v1
     - name: PullSubModUles
       run: git submodule update --init
     - name: Configure
       run: cmake .
     - name: Make
       run: make
